apiVersion: apps/v1
kind: Deployment
metadata:
  name: cafemanage
  labels:
    app: cafemanage
spec:
  replicas: 1
  selector:
    matchLabels:
      app: cafemanage
  template:
    metadata:
      labels:
        app: cafemanage
    spec:
      containers:
        - name: cafemanage
          image: username/cafemanage:latest
          ports:
            - containerPort: 8080
          readinessProbe:
            httpGet:
              path: '/actuator/health'
              port: 8080
            initialDelaySeconds: 10
            timeoutSeconds: 2
            periodSeconds: 5
            failureThreshold: 10
          livenessProbe:
            httpGet:
              path: '/actuator/health'
              port: 8080
            initialDelaySeconds: 120
            timeoutSeconds: 2
            periodSeconds: 5
            failureThreshold: 5